# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturecase_wagtail', '0002_remove_richpage_legacyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='richpage',
            name='show_kcl_logo',
            field=models.BooleanField(default=False),
        ),
    ]
