# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturecase_wagtail', '0003_richpage_show_kcl_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='richpage',
            name='short_title',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Short title'),
        ),
        migrations.AlterField(
            model_name='richpage',
            name='show_kcl_logo',
            field=models.BooleanField(default=False, verbose_name='Show KCL Logo'),
        ),
    ]
