# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturecase_wagtail', '0006_articlesummarypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesummarypage',
            name='article_authors',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Article authors'),
        ),
        migrations.AddField(
            model_name='articlesummarypage',
            name='article_date',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Article year'),
        ),
        migrations.AddField(
            model_name='articlesummarypage',
            name='article_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Article date'),
        ),
        migrations.AddField(
            model_name='articlesummarypage',
            name='article_source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Article date'),
        ),
        migrations.AddField(
            model_name='articlesummarypage',
            name='article_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Article title'),
        ),
        migrations.AddField(
            model_name='articlesummarypage',
            name='article_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Article date'),
        ),
    ]
