# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturecase_wagtail', '0007_auto_20180227_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesummarypage',
            old_name='article_date',
            new_name='article_year',
        ),
        migrations.AddField(
            model_name='articlesummarypage',
            name='article_oaurl',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Article open access link'),
        ),
        migrations.AlterField(
            model_name='articlesummarypage',
            name='article_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Article email'),
        ),
        migrations.AlterField(
            model_name='articlesummarypage',
            name='article_source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Article source'),
        ),
        migrations.AlterField(
            model_name='articlesummarypage',
            name='article_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Article link'),
        ),
    ]
