# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('culturecase_wagtail', '0009_auto_20180227_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSummaryPageResearchTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='researchtag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='researchtag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='articlesummarypage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='culturecase_wagtail.ArticleSummaryPageResearchTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='ResearchTag',
        ),
        migrations.AddField(
            model_name='articlesummarypageresearchtag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_tags', to='culturecase_wagtail.ArticleSummaryPage'),
        ),
        migrations.AddField(
            model_name='articlesummarypageresearchtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturecase_wagtail_articlesummarypageresearchtag_items', to='taggit.Tag'),
        ),
        migrations.CreateModel(
            name='ResearchTag',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('taggit.tag',),
        ),
    ]
