# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 00:53
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('culturecase_wagtail', '0011_researchcategoryhomepage_researchcategorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesummarypage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='culturecase_wagtail.ResearchCategoryPage'),
        ),
    ]
