# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-04 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturecase_wagtail', '0015_auto_20180304_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslide',
            name='background_color',
            field=models.CharField(blank=True, default=None, help_text='leave blank for transparent/white background. Or use a css color code, e.g. black or #101010 .', max_length=32, null=True),
        ),
    ]
