# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturecase_wagtail', '0016_homepageslide_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslide',
            name='text_color',
            field=models.CharField(blank=True, default=None, help_text='leave blank for black color. Or use a css color code, e.g. white or #ffffff .', max_length=32, null=True),
        ),
    ]
