# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 12:25
from __future__ import unicode_literals

from django.db import migrations


def remove_image_renditions(apps, schema_editor):
    # delete * from wagtailimages_rendition
    Rendition = apps.get_model('wagtailimages', 'Rendition')

    for rendition in Rendition.objects.all():
        rendition.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('culturecase_wagtail', '0019_auto_20180328_2256'),
    ]

    operations = [
        migrations.RunPython(remove_image_renditions),
    ]
