# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 10:59
from __future__ import unicode_literals

from django.db import migrations
from culturecase_wagtail.management.commands.ccmigrate import run_wagtail_data_migration,\
    run_wagtail_data_migration_debug, get_operation_from_migration


class Migration(migrations.Migration):

    dependencies = [
        ('culturecase_wagtail', '0022_datasectionpage'),
    ]

    operations = [
        get_operation_from_migration(migrations, debug=False),
    ]
