# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturecase_wagtail', '0023_add_menus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richpage',
            name='show_kcl_logo',
        ),
        migrations.AlterField(
            model_name='richpage',
            name='short_title',
            field=models.CharField(blank=True, default=None, help_text='A very short label used to represent this page in a menu', max_length=32, null=True, verbose_name='Menu label'),
        ),
    ]
